

github: amiaiorg
ko_fi: dxnsquantumspace
custom: ["https://www.paypal.com/donate/?business=JPJE84TDW7BBC&no_recurring=0&item_name=Looking+to+create+a+foundation+to+create+better+prosthetics+with+the+use+of+AI.&currency_code=USD"]
